project_id = "ucfgbubrgojodrkgayap"

[functions.test-api-key]
verify_jwt = false

[functions.validate-secret-code]
verify_jwt = false

[functions.generate-mermaid]
verify_jwt = false

[functions.provide-feedback]
verify_jwt = false

[functions.generate-template-analysis]
verify_jwt = false

[functions.provide-student-feedback]
verify_jwt = false

[functions.generate-phrasebank-examples]
verify_jwt = false

[functions.academic-phrasebank-chat]
verify_jwt = false

[functions.analyze-paragraph]
verify_jwt = false

[functions.pattern-analyzer]
verify_jwt = false

[functions.validate-references]
verify_jwt = false

[functions.generate-simple-activity]
verify_jwt = false

[functions.analyze-reflections]
verify_jwt = false

[functions.extract-lesson-content]
verify_jwt = false

[functions.generate-lesson]
verify_jwt = false

[functions.template-feedback]
verify_jwt = false

[functions.semantic-analysis]
verify_jwt = false

[functions.summarize-comments]
verify_jwt = false

[functions.simple-activity-chat]
verify_jwt = false

[functions.wiley-ai-guidelines-chat]
verify_jwt = false

[functions.generate-vocabulary-questions]
verify_jwt = false

[functions.create-student-account]
verify_jwt = false

[functions.send-confirmation-email]
verify_jwt = false


[functions.extract-text-from-image]
verify_jwt = false

[functions.request-email-confirmation]
verify_jwt = false

[functions.verify-email]
verify_jwt = false

[functions.request-password-reset]
verify_jwt = false

[functions.reset-password]
verify_jwt = false

